export default {
  FLAG_OBJECT: 'user:FLAG_OBJECT',
  FLAGS_LIST: 'user:FLAGS_LIST',
  CATEGORY_LIST: 'user:CATEGORY_LIST',
  UPDATE_FLAGS_LIST: 'user:UPDATE_FLAGS_LIST',
  UPDATE_FORM: 'user:UPDATE_FORM',
  DELETE_LIST: 'user:DELETE_LIST',
};
